### ISSUE TITLE
用命令行打开的资源管理器窗口不能显示图片

### ISSUE THREAD

**Issue by LS-KR** [Maplespe/explorerTool#1]
![image](https://user-images.githubusercontent.com/64070144/151637340-aab29a49-40d2-4cca-9587-636587546ead.png)
如图所示，使用命令行操作打开资源管理器时，图片没有正确加载

**Comment by Maplespe** [comment]
通过命令提示符启动的程序是独立的新进程 而通过explorer内部打开的新窗口不是独立的进程
我正在考虑使用别的方式 比如shell加载扩展到每一个explorer 但目前没有一个很好的方案

**Comment by Maplespe** [comment]
已修复
