### ISSUE TITLE
win11在进入或者退出文件夹的时候，背景会在短时间内白屏

### ISSUE THREAD

**Issue by TaJoYo** [Maplespe/explorerTool#15]
同时，高频率刷新资源管理器也会出现这种情况（低频刷新不会）

类似于闪烁的感觉，有点影响观感

这是方法的缺陷还是只有我的电脑是这样的（哭）

**Comment by ALTaleX531** [comment]
有没有可能即使没用背景插件，资源管理器也照样闪烁？

**Comment by TaJoYo** [comment]
可能是，在放图片的情况下不管主题是黑还是白都会闪烁（是黑闪黑 是白闪白），没放图片的话也没有对照，看不出来，所以我才问是不是我电脑的问题

**Comment by Maplespe** [comment]
不是电脑问题 文件资源管理器就这样

**Comment by HMwancheng** [comment]
确认不是作者的问题可以关闭这个issues /dog

**Comment by HMwancheng** [comment]
顺便吐槽这个问题win10其实是没有的，当初升级11第一时间就发现这个问题了，很烦打开文件管理器配置差了居然还要等
