### ISSUE TITLE
严重BUG：资源管理器无法打开

### ISSUE THREAD

**Issue by HMwancheng** [Maplespe/explorerTool#16]
版本1.10
系统win11

1.10版本启用后重启会导致资源管理器无法打开，提示未关联xxxx(很抱歉没有截图
桌面加载没有问题，因为无法打开资源管理器所以也无法进入文件夹内

最后使用CMD cd进入文件夹内关闭
1.9版本使用正常

**Comment by Maplespe** [comment]
> 注意事项 (Attention)
> 图片仅支持png、jpg格式 请确保为有效的图片 否则可能引发崩溃!
> 
> 如果出现崩溃 请按住ESC键再打开文件资源管理器(这不会加载图像) 然后卸载本工具或删除不兼容的图像
readme有写崩溃处理方法

另外请提供一下你的配置文件 还有最好截个图 不然我也没办法 因为我这边测试是没问题才发的。

**Comment by HMwancheng** [comment]
1.10配置文件
[load]
#指定是否在文件对话框中启用
#Specify whether or not to enable in the file dialog.
folderExt=false
#指定是否忽略错误(即出现错误不显示错误弹窗)
#Specify whether or not to ignore errors (i.e. not show error popups when errors occur).
noerror=ture
[image]
#指定图片是否随机显示 您必须放入至少两张图像
#Specifies whether the image is displayed randomly, you need to put at least 2 images
random=false
#是否启用指定自定义文件夹的图片
#Enable custom specified folder pictures
custom=false
#图片显示位置 0=左上角 1=右上角 2=左下角 3=右下角 4=居中 5=缩放 6=缩放并填充; 默认为3 右下角
#Image display position
posType=3
#图片的不透明度 范围0-255
#Alpha 0-255 of image
imgAlpha=160
#自定义图片目录绝对路径 (为空则默认 ./image)
#Custom image folder absolute path (empty defaults to . /image)
folder=

1.9配置文件
[load]
#指定是否在文件对话框中启用
#Specify whether or not to enable in the file dialog.
folderExt=false
#指定是否忽略错误(即出现错误不显示错误弹窗)
#Specify whether or not to ignore errors (i.e. not show error popups when errors occur).
noerror=ture
[image]
#指定图片是否随机显示 您必须放入至少两张图像
#Specifies whether the image is displayed randomly, you need to put at least 2 images
random=false
#是否启用指定自定义文件夹的图片
#Enable custom specified folder pictures
custom=false
#图片显示位置 0=左上角 1=右上角 2=左下角 3=右下角 4=居中 5=缩放 6=缩放并填充; 默认为3 右下角
#Image display position
posType=3
#图片的不透明度 范围0-255
#Alpha 0-255 of image
imgAlpha=160



再次下载1.10尝试，仍然无法打开资源管理器，按住ESC也不行
![Clip_230510_160655](https://github.com/Maplespe/explorerTool/assets/91036325/56794bb5-ac5a-43ef-b0cb-ff1982eb1921)

显示如下
![Clip_230510_160721](https://github.com/Maplespe/explorerTool/assets/91036325/ee454f6b-1542-4378-aadc-ef66e98a0f96)

全屏
![Clip_230510_160824](https://github.com/Maplespe/explorerTool/assets/91036325/e4d238b2-5c23-4a5d-a497-1a2ccdec2dc0)

只能使用命令行卸载
![Clip_230510_160918](https://github.com/Maplespe/explorerTool/assets/91036325/525451ac-7916-46a0-a701-b5173eee978e)

命令行卸载成功
![Clip_230510_160936](https://github.com/Maplespe/explorerTool/assets/91036325/511db7be-0bc3-49c5-9deb-f18669dc945c)

卸载后尝试打开资源管理器
![Clip_230510_161000](https://github.com/Maplespe/explorerTool/assets/91036325/6a5a09e6-4795-4bfc-b68f-f5da466660ff)



另qing请注意，即使是在任务管理器重启explorer也不行，会导致全部黑屏，桌面也无法加载

**Comment by HMwancheng** [comment]
再次下回1.9，打开，重启电脑。正常食用
![Clip_230510_161853](https://github.com/Maplespe/explorerTool/assets/91036325/b5534c58-9ea3-4579-a3c2-1705afe9e383)

**Comment by Maplespe** [comment]
folderExt=false改成folderExt=true试一试
另外你有没有安装IE浏览器 任务栏用的什么美化软件(具体版本)

**Comment by HMwancheng** [comment]
我又把1.10删掉了已经🫥

ie浏览器使用的自带，我用的这个快捷方式来启动IE
"C:\Program Files\Internet Explorer\iexplore.exe" 1.tr -Embedding

任务栏使用的Windhawk 版本1.3.1 beta
包含以下内容
![Clip_230510_163504](https://github.com/Maplespe/explorerTool/assets/91036325/32f08bbd-90d2-40ea-9a12-e285c629309b)

**Comment by HMwancheng** [comment]
另任务栏美化还包括
Translucent TB，版本为2022.1

**Comment by HMwancheng** [comment]
> folderExt=false改成folderExt=true试一试 另外你有没有安装IE浏览器 任务栏用的什么美化软件(具体版本)
![Clip_230510_170755](https://github.com/Maplespe/explorerTool/assets/91036325/b5480e29-d14d-42f1-b8c9-9b95efc0b734)


仍然失败
![Clip_230510_171150](https://github.com/Maplespe/explorerTool/assets/91036325/582dd982-319f-475f-bf62-4b262281a84e)

难受（打开cmd中）

**Comment by Maplespe** [comment]
我又安装了Translucent TB和Windhawk 包括你所选的mods 没有出现问题(软件版本和你一样)
所以可能和你的其他软件还有冲突 或者比如自启动脚本什么的 我暂时无能为力 因为我这边无法复现问题
![181206](https://github.com/Maplespe/explorerTool/assets/43676879/22afed47-9af6-4071-b931-974ea4348450)

**Comment by Maplespe** [comment]
我会再找一些物理环境来测试

**Comment by HMwancheng** [comment]
哈，没事，感谢作者大大！我在1.9也能正常使用的，不影响，再次感谢

**Comment by HMwancheng** [comment]
![Clip_230510_182521](https://github.com/Maplespe/explorerTool/assets/91036325/9222ea8b-1883-461d-aac1-d3036b4a6af8)
如果作者大大想看看其他后台软件的话，估计只有这个是最有可能影响的。不过在1.9这俩都能使用所以我也不太确定

**Comment by Maplespe** [comment]
试试这个
[Release_x64.zip](https://github.com/Maplespe/explorerTool/files/11441989/Release_x64.zip)

**Comment by HMwancheng** [comment]
> 试试这个 [Release_x64.zip](https://github.com/Maplespe/explorerTool/files/11441989/Release_x64.zip)

成功！
谢谢作者大大！

所以作者大大定位到了问题了是吗！

**Comment by Maplespe** [comment]
嗯 在多进程文件资源管理器没有初始化com组件导致加载失败 单进程没问题

**Comment by HMwancheng** [comment]
谢谢大大！！！ 大大NB !!!


（其实第一次用好像是21年，应该是用的最初版吧即使有开机启动也无法运行，今天想到这个了就去搜了一下，结果发现有人说有新版了，看见B站的名称就相起来网址好像一直在收藏夹里存着呢，真.记性不好🤣还好找到了）

**Comment by Maplespe** [comment]
没事 感谢提醒 没问题了的话就可以close了

**Comment by HMwancheng** [comment]
get！

**Comment by HMwancheng** [comment]
很抱歉再次重启此问题
这次遇到的问题和上次有点像，基本的系统条件没有改变
复现的操作是使用运行窗口打开文件夹
【win+r  然后输入  C:\Users\HM_WAN~1\AppData\Local\Temp\inputhelp\   (一个输入法在用户目录下创建的文件夹)】

然后导致桌面丢失。任务管理器打开explorer显示如下（已经无法截屏保存，手机拍摄）
![IMG_20230517_171419](https://github.com/Maplespe/explorerTool/assets/91036325/01e46fb4-f507-4cef-a88f-25bc56150b92)
重启后也是完全同样的状态

老样子，命令行卸载后桌面就自己回来了
![Clip_230517_171600](https://github.com/Maplespe/explorerTool/assets/91036325/dd027444-e8f9-4f77-9b8b-1f86d7bca5d6)

**Comment by Maplespe** [comment]
改配置文件 'noerror=true'

**Comment by HMwancheng** [comment]
可以解决吗，还是需要尝试一下

**Comment by Maplespe** [comment]
参见 #18

**Comment by HMwancheng** [comment]
> 改配置文件 'noerror=true'

目前未复现，感谢！
