### ISSUE TITLE
explorerTool is conflicting with Listary somehow.

### ISSUE THREAD

**Issue by Dhyfer1** [Maplespe/explorerTool#18]
Hi @maplespe

As the title says. [Listary](https://www.listary.com/) is a software that finds files and launches applications, it is too useful app for me.

This error that you can see in the image, which although it seems to come from Listary (I am using the latest beta version which can be downloaded [here](https://discussion.listary.com/t/6-1-0-37-beta-released/8149)), is being caused somehow by explorerTool. When explorerTool is installed, I open Listary and this error appears after entering some letters in Listary's search field. And when I click Ok from the error box, then Listary closes by itself.

![image_2](https://github.com/Maplespe/explorerTool/assets/50301201/3e94f60f-2d41-466c-a7cb-a291a7875a07)

On the contrary, when I uninstall explorerTool and open Listary, I can use Listary without any problem. So I think the error is not coming from Listary.

I have searched the internet for more info about this MTweaker error, but I have not been able to find anything about it.

I hope you can find a solution about it. Thanks in advance.

**Comment by Maplespe** [comment]
Please try to change config.ini `noerror=true`

**Comment by Dhyfer1** [comment]
> Please try to change config.ini `noerror=true`

WOW. I made the change as you said, and now I can use Listary with explorerTool installed without getting the error box 😃 I knew the problem was not coming from Listary.

Thank you very much for the solution, it really worked.

Edit: I forgot, do you know what MTweaker means?

**Comment by Dhyfer1** [comment]
Okay, as I could see in #16 MTweaker is a bug caused by explorerTool. I understand.

Thank you very much for the solution. I will now close this issue. 👍
