### ISSUE TITLE
1.0.3版本运行失败

### ISSUE THREAD

**Issue by FungueXY** [Maplespe/explorerTool#2]
注册_Register.cmd在运行后有cmd窗口弹出，但是运行失败，窗口直接消失。使用git bash直接运行注册_Register.cmd里的内容会报错，显示dll模块载入失败。系统是win10 19042.1466 20H2。
日志因为不知道怎么引出所以没有。

**Comment by Maplespe** [comment]
正常情况下运行Register应当弹出一个UAC对话框 然后确定后弹出DllRegisterServer的对话框 而不是直接消失
您是否具有管理员权限?并授予本次操作
或者尝试手动运行 以管理员身份
`regsvr32 "您的路径\ExplorerBgTool.dll"`

**Comment by FungueXY** [comment]
已解决。使用管理员权限单独启动cmd程序后注册dll组件成功。非常感谢。
