### ISSUE TITLE
文件属性下以前的版本这一栏也出现了背景图

### ISSUE THREAD

**Issue by llxlr** [Maplespe/explorerTool#24]
![image](https://github.com/Maplespe/explorerTool/assets/33483752/a5471f2e-c5f5-4cd9-8d25-db0603f067c7)

**Comment by Maplespe** [comment]
实际上新版本为了兼容"打开文件对话框"不得不放宽了检查范围 这个界面的列表实际上和文件资源管理器的列表是同一种控件
而且使用第三方主题实现的文件夹背景效果也有这样的效果 所以我不认为他是bug
如果你介意的话可以先用1.0.8版本
