### ISSUE TITLE
There is no any dll file in source code.

### ISSUE THREAD

**Issue by john9999911** [Maplespe/explorerTool#7]
可以让我白嫖到底吗，电脑上没vs做不了生成dll工作捏
阿里嘎多~

**Comment by Maplespe** [comment]
编译好的程序在 [Release页面](https://github.com/Maplespe/explorerTool/releases)

**Comment by john9999911** [comment]
> 编译好的程序在 [Release页面](https://github.com/Maplespe/explorerTool/releases)

感谢您对盲人的贴心指导qwq
