### ISSUE TITLE
Two feature requests I would like to see

### ISSUE THREAD

**Issue by Dhyfer1** [Maplespe/explorerTool#8]
Hi @Maplespe 

Thank you very much for explorerTool, I like it very much but to make it more attractive I would like it to have these two features:

1. That the background image can also be seen in the Open/Save File dialog box.

![image_1](https://user-images.githubusercontent.com/50301201/196945152-d046df22-b12e-4df0-8974-8b2e220cd4c5.png)

2. I would like to see a different custom image (and that the image doesn't change) in the 6 main folders that appear in Home: 
- Desktop
- Downloads
- Documents
- Pictures
- Videos 
- Music

That's all, what do you say about it?

**Comment by Maplespe** [comment]
About Open/Save File dialog box, I can only make it effective for Explorer
Because this program will not be loaded into external programs, I do not intend to provide it.
However, I can implement the function of using different images in different folders in the next version.

Thank you for your advice.

**Comment by Dhyfer1** [comment]
> About Open/Save File dialog box, I can only make it effective for Explorer Because this program will not be loaded into external programs, I do not intend to provide it. 

Do you mean that if I, for example, want to open an image for editing from a web site (like [Photopea](https://www.photopea.com/)), the background image of the file explorer will not be displayed as background in the dialog box? or, for example, if I use Paint and I want to open an image file, will the background image not be visible either?

>However, I can implement the function of using different images in different folders in the next version.

Great, thank you! I look forward to the next version

**Comment by Maplespe** [comment]
> Do you mean that if I, for example, want to open an image for editing from a web site (like [Photopea](https://www.photopea.com/)), the background image of the file explorer will not be displayed as background in the dialog box? or, for example, if I use Paint and I want to open an image file, will the background image not be visible either?

Yes, actually these are external programs, and my dll will not be loaded by them

**Comment by Dhyfer1** [comment]
> Yes, actually these are external programs, and my dll will not be loaded by them

I understand, but it would be great if the background image could also be seen in the Open/Save dialog box from external programs. Can't you really do anything about it?

>About Open/Save File dialog box, I can only make it effective for Explorer

How can you open the Open/Save dialog box from the file explorer? When I open the file explorer and press <kbd>Ctrl</kbd>+<kbd>O</kbd> a dialog box different from the one shown in the image above appear.

**Comment by Maplespe** [comment]
I have released an update [Release ](https://github.com/Maplespe/explorerTool/releases/tag/1.0.7)on the function of using different images in different folders.
Please refer to the [ReadMe.md](https://github.com/Maplespe/explorerTool#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-config) for usage.

> I understand, but it would be great if the background image could also be seen in the Open/Save dialog box from external programs. Can't you really do anything about it?

At present, to achieve external program effects without patching system files, you may need to inject dll globally
I think this is a very expensive and unstable approach
So at the moment, there is no better way for me to... I'm sorry

**Comment by Dhyfer1** [comment]
> I have released an update [Release ](https://github.com/Maplespe/explorerTool/releases/tag/1.0.7)on the function of using different images in different folders. Please refer to the [ReadMe.md](https://github.com/Maplespe/explorerTool#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-config) for usage.

Hi, the new version works very well. I have customized each of the six Home folders with a different image. But there is a problem, when I open any folder from any different path (e.g. C:\Windows, C:\Program Files (x86), C:\Users\diego\AppData, etc...) the background image is the same image of the Desktop folder. Is it possible that the other folders that do not belong to Home share the same image?

When I met explorerTool for the first time, I installed the latest version at that moment (1.0.6) and there was only one image in the Image folder, that image appeared as background in any folder I opened. This last one is what I want, that explorerTool shows the same background image in the other different folders of Home.

> At present, to achieve external program effects without patching system files, you may need to inject dll globally I think this is a very expensive and unstable approach So at the moment, there is no better way for me to... I'm sorry

It's a shame to hear that, but you said this before: _About Open/Save File dialog box, I can only make it effective for Explorer_ So, if your dll can't be loaded by external programs, at least it can be loaded for Open/Save dialog boxes opened within the file explorer?

**Comment by Maplespe** [comment]
Is your system version 22H2? If so, you can try to use the latest version (1.0.8), which solves some bugs in multiple tabs
There is a method for pinning pictures in other folders:
1. Rename the image you want to display fixedly to `1.png` or another name, but make sure it always ranks first
2. Set `Config. ini` `random=false`
> It's a shame to hear that, but you said this before: About Open/Save File dialog box, I can only make it effective for Explorer So, if your dll can't be loaded by external programs, at least it can be loaded for Open/Save dialog boxes opened within the file explorer?

Yes, but it needs to be changed a lot. Because it is rare to open this dialog box in Explorer, I did not complete it at that time
But it should be feasible, but I have something to do so I won't make any major changes in the short term
I will provide it in the future if necessary

**Comment by Dhyfer1** [comment]
Hi, Thanks for the workaround. I renamed an image as 1.png and this image now appears as background in every folder that doesn't belong to Home, which is exactly what I needed.

>Yes, but it needs to be changed a lot. Because it is rare to open this dialog box in Explorer, I did not complete it at that time
But it should be feasible, but I have something to do so I won't make any major changes in the short term
I will provide it in the future if necessary

Okay, I can wait. But I don't know how to open the Open/Save dialog box inside the file explorer. As I said before, when I press Ctrl+O a totally different dialog box appears.

**Comment by Maplespe** [comment]
Hi, I have added a new feature to show images in the file dialog.
Please see ReadMe and Release for more details.

**Comment by Dhyfer1** [comment]
> Hi, I have added a new feature to show images in the file dialog. Please see [ReadMe](https://github.com/Maplespe/explorerTool#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-config) and [Release](https://github.com/Maplespe/explorerTool/releases) for more details.

Hi. Thanks for the new version, it works fine. Well, I want to say that this new version has a bug. When a web site or a program calls the Open/Save dialog box, the custom background image doesn't appear (I only get a dialog box with no image, like in the image in my first comment), the background image only appears when I open any folder inside the dialog box. No matter how many times the dialog box appears, it always appears without background image and I can only see the background image when I open a folder inside the dialog box.

That's it, it's just that bug.
Thanks.

**Comment by Maplespe** [comment]
Fixed, please check the latest [Release](https://github.com/Maplespe/explorerTool/releases/tag/1.1.0).

**Comment by Dhyfer1** [comment]
Thanks for fixing the bug, now the background image is displayed the first time the dialog box is opened. 👍

In version 1.1.0 according to the release note it says: _Added configuration options for custom image folders (see [Config](https://github.com/Maplespe/explorerTool#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-config) for details)._ I just don't understand how it works. In the config.ini file there is now this new configuration:
```ini
[image]
#Custom image folder absolute path (empty defaults to . /image)
folder=
``` 
When I unzip the explorerTool file, inside there is a folder named Image, inside this Image folder I have placed images to customize different folders (Desktop, Downloads, Documents etc). Is this Image folder no longer the default folder used by explorerTool to assign background images for various folders? 

As I said before, I don't understand this new configuration. Until now, to add custom images to a particular folder, I would place the image in the Image folder and in the config.ini file I would use this:
```ini
[image]
custom=true

#Please put the picture in the Image folder first, and then img=specify the file name in the Image folder Is the file name, not the full path!
#Some special folder paths are CLSID For example:
#This PC
#::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
#Quick access
#::{679F85CB-0220-4080-B29B-5540CC05AAB6}
#Network
#::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}

#(Example)
[::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]
img=myimage.png

[C:\Users\admin\Pictures\Camera Roll]
img=mypic.png
#(Takes effect as soon as the file is saved)
```
What changes now?

**Comment by Maplespe** [comment]
If this option is left blank, it is exactly the same as before.
If you set a path, the default folder will be the path you set.
That is, you now need to put the image files in the new path you have set.
Other than that, there is no difference from before.

**Comment by Dhyfer1** [comment]
I was confused so thanks for the clarification, now I understand. So it's just another option if I want to use a particular folder other than the Image folder, that's fine.

One last thing I want to say is:

1. Can you add support for SVG files?
2. Can you add another cloud storage service for non-Chinese users like me who want to download your [toolbox](https://winmoes.com/tools/12948.html)? I want to use your toolbox, but I don't have a Baidu or QQ account to download it. You could think of services like Mega, OneDrive etc.

That's all

**Comment by Maplespe** [comment]
1. for svg generally it is used for vector icons, and the folder background is generally in a small size. So I think it is not very meaningful, mainly because it needs to introduce third-party svg library, which makes the program more complicated, so I may not plan to introduce it for now.
2. for toolbox I have added the download link of Google Dirve, now you can find it in the page.
However, please note that the current update progress of the toolbox is far less than the open source components.

**Comment by Dhyfer1** [comment]
1. Well, sometimes some images appear pixelated when I use the Stretch or Zoom and fill option, and I thought that to avoid that problem it would be better if explorerTool also had support for svg files, since svg images can be enlarged and reduced without losing resolution. I hope someday to be able to use svg files with explorerTool, if possible.

2. I have translated the page into English, clicked on the Google Drive link and this appears:
![Untitled](https://user-images.githubusercontent.com/50301201/236594897-dbf2afa1-6cfa-4e4e-8376-cb41c3146328.png)
Only that nothing happens when I click on Register. By the way, I forgot. Your toolbox comes in English? and can it work together with explorerTool?

**Comment by Maplespe** [comment]
Please click on the "Register" button on the webpage instead of the "Login" link.
The Toolbox can be used in conjunction with this project (but it is not recommended, as the Toolbox already contains this functionality).
Also, the toolbox is only available in Chinese and there is no English translation yet.

**Comment by Dhyfer1** [comment]
Ok, I was able to register and I have downloaded the tool. I know that the toolbox has an option equal to explorerTool, but I'm not interested. There are other functions in toolbox that catch my attention.

I hope that in the future you will add English language to your toolbox.

**Comment by Dhyfer1** [comment]
Since the two features I asked for in this issue were resolved thanks to the developer, so I am closing this issue. I hope explorerTool can later have support for SVG files.

That's all. Thank you so much.
